#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 26 20:02:23 2020

@author: nj1000275242
"""

from math import *

def square_rooted(x):
    return round(sqrt(sum(a*a for a in x)), 3)

def cosine_similarity(x, y):
    numerator = sum(a*b for a, b in zip(x, y))
    denominator = square_rooted(x) * square_rooted(y)
    return round(numerator/float(denominator), 3)

print(cosine_similarity([3, 45, 7, 2], [2, 52, 13, 15]))